{% set name = "pip2conda" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pip2conda-{{ version }}.tar.gz
  sha256: bd2478db48e4b5f92fd7171f25fda54d7b592bb70bca6611e5de0f0ac1c74b81

build:
  entry_points:
    - pip2conda = pip2conda.pip2conda:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools >=61.0
    - setuptools-scm >=3.4.3
  run:
    - grayskull >=1.0.0
    - packaging
    - python >=3.10
    - python-build >=1.0.0
    - requests
    - ruamel.yaml
    - wheel

test:
  requires:
    - pip
    - pytest
  commands:
    # check metadata
    - python -m pip check pip2conda
    - python -m pip show pip2conda
    # run test suite
    - python -m pytest -ra -v --pyargs pip2conda.tests -k "not real"
    # test entry point
    - pip2conda --help

about:
  home: https://github.com/duncanmmacleod/pip2conda/
  dev_url: https://github.com/duncanmmacleod/pip2conda.git
  doc_url: https://pip2conda.readthedocs.io/
  summary: Translate pip requirements into conda requirements
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  description: |
    `pip2conda` is a tool to translate `pip`-style requirements into `conda`
    requirements.

    `pip2conda2` uses [`build`](https://github.com/pypa/build) to generate
    the metadata for a project, and then parses out the build and
    runtime requirements for the project - including unpackging extras and
    evaluating environment markers - before matching translating each requirement
    into a conda-forge requirement suitable for installation with `conda/mamba`.

extra:
  recipe-maintainers:
    - duncanmmacleod
