{% set name = "pip2conda" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pip2conda-{{ version }}.tar.gz
  sha256: 0838ed595e60c93c92b8a50b135893314b8ece28bd3c1aa3e059c87520ab9e5d

build:
  entry_points:
    - pip2conda = pip2conda.pip2conda:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - setuptools-scm
  run:
    - grayskull >=1.0.0
    - python >=3.8
    - requests
    - ruamel.yaml
    - setuptools
    - tomli

test:
  requires:
    - pip
    - pytest
  commands:
    # check metadata
    - python -m pip check
    # run test suite
    - python -m pytest -ra -v --pyargs pip2conda.tests -k "not real"
    # test entry point
    - pip2conda --help

about:
  home: https://github.com/duncanmmacleod/pip2conda/
  dev_url: https://github.com/duncanmmacleod/pip2conda.git
  doc_url: https://pip2conda.readthedocs.io/
  summary: Translate pip requirements into conda requirements
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  description: |
    `pip2conda` is a tool to translate `pip`-style requirements into `conda`
    requirements.

    `pip2conda` parses build requirements from ``pyproject.toml`` files, then
    runtime and extra requirements from ``setup.cfg``, including unpackging
    extras and evaluating environment markers, before matching translating
    each requirement into a conda-forge requirement suitable for installation
    with `conda/mamba`.

extra:
  recipe-maintainers:
    - duncanmmacleod
