schema_version: 1

context:
  name: pip2conda
  version: 0.9.1
  python_min: 3.11

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 8d45bc37f192bf9fc942b4a637fae7565e8ca67bbe13ba5755a48ae0a47029f6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - pip2conda = pip2conda.pip2conda:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - setuptools-scm >=3.4.3
  run:
    - grayskull >=2.9.2
    - packaging >=25.0
    - python >=${{ python_min }}
    - python-build >=1.0.0
    - requests >=2.32.5
    - ruamel.yaml >=0.18.15
    - wheel >=0.46.2

tests:
  - requirements:
      run:
        - pip
        - pytest >=8.4.1
        - python ${{ python_min }}.*
    script:
      # Check metadata
      - python -m pip check pip2conda
      - python -m pip show pip2conda
      # Run test suite
      - python -m pytest -ra -v --pyargs pip2conda.tests -k "not real"
      # Check entry point
      - pip2conda --help

about:
  summary: Translate pip requirements into conda requirements
  description: |
    `pip2conda` is a tool to translate `pip`-style requirements into `conda`
    requirements.

    `pip2conda2` uses [`build`](https://github.com/pypa/build) to generate
    the metadata for a project, and then parses out the build and
    runtime requirements for the project - including unpackging extras and
    evaluating environment markers - before matching translating each requirement
    into a conda-forge requirement suitable for installation with `conda/mamba`.
  homepage: https://gitlab.com/gwpy/pip2conda/
  repository: https://gitlab.com/gwpy/pip2conda.git
  documentation: https://pip2conda.readthedocs.io/
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - duncanmmacleod
